/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ControlsHint: typeof import('./../components/game/ControlsHint.vue')['default']
    EffectSwitcher: typeof import('./../components/EffectSwitcher.vue')['default']
    GameInfoPanel: typeof import('./../components/game/GameInfoPanel.vue')['default']
    GameStatus: typeof import('./../components/game/GameStatus.vue')['default']
    MapControls: typeof import('./../components/MapControls.vue')['default']
    PanoramaViewer: typeof import('./../components/PanoramaViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WebGPUNotSupported: typeof import('./../components/WebGPUNotSupported.vue')['default']
  }
}
