/**
 * 儿童英语打字词库
 *
 * 数据结构：WordItem { word, zh, phonetic }
 * wordBankData[难度][主题] = WordItem[]  ← 大词库，每局随机抽取
 */

export interface WordItem {
  word: string
  zh: string
  phonetic: string
}

/* ─── 随机打乱数组（Fisher-Yates） ─────────────────────────────────── */
export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

/* ─── 从大词库随机抽取 n 个不重复词 ────────────────────────────────── */
export function pickRandom(pool: WordItem[], n: number): WordItem[] {
  return shuffle(pool).slice(0, Math.min(n, pool.length))
}

/* ═══════════════════════════════════════════════════════════════════
   大词库 —— 每个主题 30+ 个词
═══════════════════════════════════════════════════════════════════ */

/** 简单模式大词库 */
export const easyPool: WordItem[] = [
  // 🐾 动物
  { word: 'cat', zh: '猫咪', phonetic: '/kæt/' },
  { word: 'dog', zh: '小狗', phonetic: '/dɒɡ/' },
  { word: 'pig', zh: '小猪', phonetic: '/pɪɡ/' },
  { word: 'cow', zh: '奶牛', phonetic: '/kaʊ/' },
  { word: 'hen', zh: '母鸡', phonetic: '/hɛn/' },
  { word: 'fox', zh: '狐狸', phonetic: '/fɒks/' },
  { word: 'owl', zh: '猫头鹰', phonetic: '/aʊl/' },
  { word: 'bee', zh: '蜜蜂', phonetic: '/biː/' },
  { word: 'ant', zh: '蚂蚁', phonetic: '/ænt/' },
  { word: 'bat', zh: '蝙蝠', phonetic: '/bæt/' },
  { word: 'rat', zh: '老鼠', phonetic: '/ræt/' },
  { word: 'bug', zh: '小虫子', phonetic: '/bʌɡ/' },
  { word: 'ram', zh: '公羊', phonetic: '/ræm/' },
  { word: 'cub', zh: '幼兽', phonetic: '/kʌb/' },
  { word: 'emu', zh: '鸸鹋', phonetic: '/ˈiːmjuː/' },
  { word: 'yak', zh: '牦牛', phonetic: '/jæk/' },
  { word: 'jay', zh: '松鸦', phonetic: '/dʒeɪ/' },
  // 🌈 颜色
  { word: 'red', zh: '红色', phonetic: '/rɛd/' },
  { word: 'blue', zh: '蓝色', phonetic: '/bluː/' },
  { word: 'pink', zh: '粉色', phonetic: '/pɪŋk/' },
  { word: 'gold', zh: '金色', phonetic: '/ɡəʊld/' },
  { word: 'gray', zh: '灰色', phonetic: '/ɡreɪ/' },
  { word: 'cyan', zh: '青色', phonetic: '/ˈsaɪæn/' },
  { word: 'lime', zh: '黄绿色', phonetic: '/laɪm/' },
  { word: 'rose', zh: '玫瑰红', phonetic: '/rəʊz/' },
  { word: 'teal', zh: '蓝绿色', phonetic: '/tiːl/' },
  { word: 'navy', zh: '深蓝色', phonetic: '/ˈneɪvi/' },
  { word: 'jade', zh: '翡翠绿', phonetic: '/dʒeɪd/' },
  { word: 'plum', zh: '紫红色', phonetic: '/plʌm/' },
  { word: 'tan', zh: '棕褐色', phonetic: '/tæn/' },
  { word: 'ink', zh: '墨色', phonetic: '/ɪŋk/' },
  // 👀 身体部位
  { word: 'eye', zh: '眼睛', phonetic: '/aɪ/' },
  { word: 'ear', zh: '耳朵', phonetic: '/ɪər/' },
  { word: 'arm', zh: '手臂', phonetic: '/ɑːm/' },
  { word: 'leg', zh: '腿', phonetic: '/lɛɡ/' },
  { word: 'lip', zh: '嘴唇', phonetic: '/lɪp/' },
  { word: 'rib', zh: '肋骨', phonetic: '/rɪb/' },
  { word: 'hip', zh: '臀部', phonetic: '/hɪp/' },
  { word: 'jaw', zh: '下巴', phonetic: '/dʒɔː/' },
  { word: 'toe', zh: '脚趾', phonetic: '/təʊ/' },
  { word: 'knee', zh: '膝盖', phonetic: '/niː/' },
  { word: 'back', zh: '背部', phonetic: '/bæk/' },
  { word: 'nose', zh: '鼻子', phonetic: '/nəʊz/' },
  { word: 'hair', zh: '头发', phonetic: '/hɛər/' },
  { word: 'hand', zh: '手', phonetic: '/hænd/' },
  { word: 'foot', zh: '脚', phonetic: '/fʊt/' },
  { word: 'face', zh: '脸', phonetic: '/feɪs/' },
  { word: 'chin', zh: '下巴', phonetic: '/tʃɪn/' },
  // 🏠 家里的东西
  { word: 'bed', zh: '床', phonetic: '/bɛd/' },
  { word: 'cup', zh: '杯子', phonetic: '/kʌp/' },
  { word: 'fan', zh: '风扇', phonetic: '/fæn/' },
  { word: 'jar', zh: '罐子', phonetic: '/dʒɑː/' },
  { word: 'key', zh: '钥匙', phonetic: '/kiː/' },
  { word: 'lamp', zh: '台灯', phonetic: '/læmp/' },
  { word: 'door', zh: '门', phonetic: '/dɔː/' },
  { word: 'sofa', zh: '沙发', phonetic: '/ˈsəʊfə/' },
  { word: 'desk', zh: '书桌', phonetic: '/dɛsk/' },
  { word: 'book', zh: '书', phonetic: '/bʊk/' },
  { word: 'bowl', zh: '碗', phonetic: '/bəʊl/' },
  { word: 'fork', zh: '叉子', phonetic: '/fɔːk/' },
  { word: 'mat', zh: '垫子', phonetic: '/mæt/' },
  { word: 'pan', zh: '平底锅', phonetic: '/pæn/' },
  { word: 'pot', zh: '锅', phonetic: '/pɒt/' },
  { word: 'mug', zh: '马克杯', phonetic: '/mʌɡ/' },
  { word: 'rug', zh: '地毯', phonetic: '/rʌɡ/' },
  { word: 'box', zh: '箱子', phonetic: '/bɒks/' },
  { word: 'bag', zh: '袋子', phonetic: '/bæɡ/' },
  { word: 'hat', zh: '帽子', phonetic: '/hæt/' },
  // 🌿 大自然
  { word: 'sun', zh: '太阳', phonetic: '/sʌn/' },
  { word: 'sky', zh: '天空', phonetic: '/skaɪ/' },
  { word: 'sea', zh: '大海', phonetic: '/siː/' },
  { word: 'mud', zh: '泥土', phonetic: '/mʌd/' },
  { word: 'leaf', zh: '树叶', phonetic: '/liːf/' },
  { word: 'rain', zh: '雨', phonetic: '/reɪn/' },
  { word: 'wind', zh: '风', phonetic: '/wɪnd/' },
  { word: 'snow', zh: '雪', phonetic: '/snəʊ/' },
  { word: 'rock', zh: '石头', phonetic: '/rɒk/' },
  { word: 'tree', zh: '大树', phonetic: '/triː/' },
  { word: 'moon', zh: '月亮', phonetic: '/muːn/' },
  { word: 'star', zh: '星星', phonetic: '/stɑː/' },
  { word: 'fog', zh: '雾', phonetic: '/fɒɡ/' },
  { word: 'ice', zh: '冰', phonetic: '/aɪs/' },
  { word: 'dew', zh: '露水', phonetic: '/djuː/' },
  { word: 'bay', zh: '海湾', phonetic: '/beɪ/' },
  { word: 'log', zh: '原木', phonetic: '/lɒɡ/' },
  { word: 'sand', zh: '沙子', phonetic: '/sænd/' },
  { word: 'seed', zh: '种子', phonetic: '/siːd/' },
  { word: 'vine', zh: '藤蔓', phonetic: '/vaɪn/' },
  // 🔢 数字与形状
  { word: 'one', zh: '一', phonetic: '/wʌn/' },
  { word: 'two', zh: '二', phonetic: '/tuː/' },
  { word: 'six', zh: '六', phonetic: '/sɪks/' },
  { word: 'ten', zh: '十', phonetic: '/tɛn/' },
  { word: 'dot', zh: '点', phonetic: '/dɒt/' },
  { word: 'oval', zh: '椭圆', phonetic: '/ˈəʊvəl/' },
  { word: 'cube', zh: '正方体', phonetic: '/kjuːb/' },
  { word: 'cone', zh: '圆锥', phonetic: '/kəʊn/' },
  { word: 'ring', zh: '圆环', phonetic: '/rɪŋ/' },
  { word: 'line', zh: '直线', phonetic: '/laɪn/' },
]

/** 普通模式大词库 */
export const normalPool: WordItem[] = [
  // 🍎 水果
  { word: 'apple', zh: '苹果', phonetic: '/ˈæpəl/' },
  { word: 'grape', zh: '葡萄', phonetic: '/ɡreɪp/' },
  { word: 'lemon', zh: '柠檬', phonetic: '/ˈlɛmən/' },
  { word: 'mango', zh: '芒果', phonetic: '/ˈmæŋɡəʊ/' },
  { word: 'melon', zh: '甜瓜', phonetic: '/ˈmɛlən/' },
  { word: 'peach', zh: '桃子', phonetic: '/piːtʃ/' },
  { word: 'guava', zh: '番石榴', phonetic: '/ˈɡwɑːvə/' },
  { word: 'olive', zh: '橄榄', phonetic: '/ˈɒlɪv/' },
  { word: 'berry', zh: '浆果', phonetic: '/ˈbɛri/' },
  { word: 'pear', zh: '梨子', phonetic: '/pɛər/' },
  { word: 'kiwi', zh: '猕猴桃', phonetic: '/ˈkiːwiː/' },
  { word: 'plum', zh: '李子', phonetic: '/plʌm/' },
  { word: 'lime', zh: '青柠', phonetic: '/laɪm/' },
  { word: 'date', zh: '枣子', phonetic: '/deɪt/' },
  { word: 'fig', zh: '无花果', phonetic: '/fɪɡ/' },
  { word: 'cherry', zh: '樱桃', phonetic: '/ˈtʃɛri/' },
  { word: 'papaya', zh: '木瓜', phonetic: '/pəˈpaɪə/' },
  { word: 'banana', zh: '香蕉', phonetic: '/bəˈnɑːnə/' },
  { word: 'orange', zh: '橙子', phonetic: '/ˈɒrɪndʒ/' },
  { word: 'lychee', zh: '荔枝', phonetic: '/ˈlaɪtʃiː/' },
  { word: 'durian', zh: '榴莲', phonetic: '/ˈdʊəriən/' },
  { word: 'pitaya', zh: '火龙果', phonetic: '/pɪˈtaɪə/' },
  { word: 'longan', zh: '龙眼', phonetic: '/ˈlɒŋɡən/' },
  // 🍕 食物
  { word: 'bread', zh: '面包', phonetic: '/brɛd/' },
  { word: 'cake', zh: '蛋糕', phonetic: '/keɪk/' },
  { word: 'candy', zh: '糖果', phonetic: '/ˈkændi/' },
  { word: 'chips', zh: '薯片', phonetic: '/tʃɪps/' },
  { word: 'cream', zh: '奶油', phonetic: '/kriːm/' },
  { word: 'juice', zh: '果汁', phonetic: '/dʒuːs/' },
  { word: 'pizza', zh: '披萨', phonetic: '/ˈpiːtsə/' },
  { word: 'salad', zh: '沙拉', phonetic: '/ˈsæləd/' },
  { word: 'sauce', zh: '酱料', phonetic: '/sɔːs/' },
  { word: 'sugar', zh: '糖', phonetic: '/ˈʃʊɡər/' },
  { word: 'toast', zh: '吐司', phonetic: '/təʊst/' },
  { word: 'waffle', zh: '华夫饼', phonetic: '/ˈwɒfəl/' },
  { word: 'honey', zh: '蜂蜜', phonetic: '/ˈhʌni/' },
  { word: 'noodle', zh: '面条', phonetic: '/ˈnuːdəl/' },
  { word: 'butter', zh: '黄油', phonetic: '/ˈbʌtər/' },
  { word: 'cookie', zh: '曲奇饼', phonetic: '/ˈkʊki/' },
  { word: 'fudge', zh: '软糖', phonetic: '/fʌdʒ/' },
  { word: 'muffin', zh: '松饼', phonetic: '/ˈmʌfɪn/' },
  { word: 'pancake', zh: '煎饼', phonetic: '/ˈpænkeɪk/' },
  { word: 'popcorn', zh: '爆米花', phonetic: '/ˈpɒpkɔːn/' },
  { word: 'pretzel', zh: '椒盐饼干', phonetic: '/ˈprɛtsəl/' },
  // 🦁 可爱动物
  { word: 'horse', zh: '马', phonetic: '/hɔːs/' },
  { word: 'shark', zh: '鲨鱼', phonetic: '/ʃɑːk/' },
  { word: 'tiger', zh: '老虎', phonetic: '/ˈtaɪɡər/' },
  { word: 'whale', zh: '鲸鱼', phonetic: '/weɪl/' },
  { word: 'zebra', zh: '斑马', phonetic: '/ˈziːbrə/' },
  { word: 'eagle', zh: '老鹰', phonetic: '/ˈiːɡəl/' },
  { word: 'koala', zh: '考拉', phonetic: '/kəʊˈɑːlə/' },
  { word: 'llama', zh: '羊驼', phonetic: '/ˈlɑːmə/' },
  { word: 'moose', zh: '驼鹿', phonetic: '/muːs/' },
  { word: 'otter', zh: '水獭', phonetic: '/ˈɒtər/' },
  { word: 'panda', zh: '熊猫', phonetic: '/ˈpændə/' },
  { word: 'robin', zh: '知更鸟', phonetic: '/ˈrɒbɪn/' },
  { word: 'bison', zh: '野牛', phonetic: '/ˈbaɪsən/' },
  { word: 'camel', zh: '骆驼', phonetic: '/ˈkæməl/' },
  { word: 'cobra', zh: '眼镜蛇', phonetic: '/ˈkəʊbrə/' },
  { word: 'crane', zh: '仙鹤', phonetic: '/kreɪn/' },
  { word: 'goose', zh: '鹅', phonetic: '/ɡuːs/' },
  { word: 'hyena', zh: '鬣狗', phonetic: '/haɪˈiːnə/' },
  { word: 'jaguar', zh: '美洲豹', phonetic: '/ˈdʒæɡjuər/' },
  { word: 'lemur', zh: '狐猴', phonetic: '/ˈliːmər/' },
  { word: 'lynx', zh: '猞猁', phonetic: '/lɪŋks/' },
  { word: 'parrot', zh: '鹦鹉', phonetic: '/ˈpærət/' },
  // 🎮 玩具与游戏
  { word: 'block', zh: '积木', phonetic: '/blɒk/' },
  { word: 'chess', zh: '象棋', phonetic: '/tʃɛs/' },
  { word: 'drone', zh: '无人机', phonetic: '/drəʊn/' },
  { word: 'flute', zh: '长笛', phonetic: '/fluːt/' },
  { word: 'kite', zh: '风筝', phonetic: '/kaɪt/' },
  { word: 'robot', zh: '机器人', phonetic: '/ˈrəʊbɒt/' },
  { word: 'slide', zh: '滑梯', phonetic: '/slaɪd/' },
  { word: 'swing', zh: '秋千', phonetic: '/swɪŋ/' },
  { word: 'train', zh: '小火车', phonetic: '/treɪn/' },
  { word: 'magic', zh: '魔法', phonetic: '/ˈmædʒɪk/' },
  { word: 'balloon', zh: '气球', phonetic: '/bəˈluːn/' },
  { word: 'camera', zh: '相机', phonetic: '/ˈkæmərə/' },
  { word: 'castle', zh: '城堡', phonetic: '/ˈkɑːsəl/' },
  { word: 'crayon', zh: '蜡笔', phonetic: '/ˈkreɪɒn/' },
  { word: 'frisbee', zh: '飞盘', phonetic: '/ˈfrɪzbiː/' },
  { word: 'guitar', zh: '吉他', phonetic: '/ɡɪˈtɑː/' },
  { word: 'jigsaw', zh: '拼图', phonetic: '/ˈdʒɪɡsɔː/' },
  { word: 'marble', zh: '弹珠', phonetic: '/ˈmɑːbəl/' },
  { word: 'puzzle', zh: '谜题', phonetic: '/ˈpʌzəl/' },
  // 🏫 学校生活
  { word: 'class', zh: '班级', phonetic: '/klɑːs/' },
  { word: 'color', zh: '颜色', phonetic: '/ˈkʌlər/' },
  { word: 'eraser', zh: '橡皮擦', phonetic: '/ɪˈreɪzər/' },
  { word: 'globe', zh: '地球仪', phonetic: '/ɡləʊb/' },
  { word: 'grade', zh: '年级', phonetic: '/ɡreɪd/' },
  { word: 'lunch', zh: '午饭', phonetic: '/lʌntʃ/' },
  { word: 'paper', zh: '纸张', phonetic: '/ˈpeɪpər/' },
  { word: 'pencil', zh: '铅笔', phonetic: '/ˈpɛnsəl/' },
  { word: 'recess', zh: '课间休息', phonetic: '/ˈriːsɛs/' },
  { word: 'ruler', zh: '尺子', phonetic: '/ˈruːlər/' },
  { word: 'school', zh: '学校', phonetic: '/skuːl/' },
  { word: 'chalk', zh: '粉笔', phonetic: '/tʃɔːk/' },
  { word: 'compass', zh: '圆规', phonetic: '/ˈkʌmpəs/' },
  { word: 'diary', zh: '日记本', phonetic: '/ˈdaɪəri/' },
  { word: 'folder', zh: '文件夹', phonetic: '/ˈfəʊldər/' },
  { word: 'glue', zh: '胶水', phonetic: '/ɡluː/' },
  { word: 'marker', zh: '马克笔', phonetic: '/ˈmɑːkər/' },
  { word: 'notebook', zh: '笔记本', phonetic: '/ˈnəʊtbʊk/' },
  { word: 'scissors', zh: '剪刀', phonetic: '/ˈsɪzərz/' },
]

/** 困难模式大词库 */
export const hardPool: WordItem[] = [
  // ⚽ 运动与冒险
  { word: 'baseball', zh: '棒球', phonetic: '/ˈbeɪsbɔːl/' },
  { word: 'bowling', zh: '保龄球', phonetic: '/ˈbəʊlɪŋ/' },
  { word: 'camping', zh: '野营', phonetic: '/ˈkæmpɪŋ/' },
  { word: 'cycling', zh: '骑自行车', phonetic: '/ˈsaɪklɪŋ/' },
  { word: 'fishing', zh: '钓鱼', phonetic: '/ˈfɪʃɪŋ/' },
  { word: 'hiking', zh: '徒步旅行', phonetic: '/ˈhaɪkɪŋ/' },
  { word: 'jumping', zh: '跳跃', phonetic: '/ˈdʒʌmpɪŋ/' },
  { word: 'skating', zh: '溜冰', phonetic: '/ˈskeɪtɪŋ/' },
  { word: 'surfing', zh: '冲浪', phonetic: '/ˈsɜːfɪŋ/' },
  { word: 'swimming', zh: '游泳', phonetic: '/ˈswɪmɪŋ/' },
  { word: 'wrestling', zh: '摔跤', phonetic: '/ˈrɛslɪŋ/' },
  { word: 'archery', zh: '射箭', phonetic: '/ˈɑːtʃəri/' },
  { word: 'badminton', zh: '羽毛球', phonetic: '/ˈbædmɪntən/' },
  { word: 'climbing', zh: '攀岩', phonetic: '/ˈklaɪmɪŋ/' },
  { word: 'fencing', zh: '击剑', phonetic: '/ˈfɛnsɪŋ/' },
  { word: 'football', zh: '足球', phonetic: '/ˈfʊtbɔːl/' },
  { word: 'gymnastics', zh: '体操', phonetic: '/dʒɪmˈnæstɪks/' },
  { word: 'handball', zh: '手球', phonetic: '/ˈhændbɔːl/' },
  { word: 'hurdles', zh: '跨栏', phonetic: '/ˈhɜːdəlz/' },
  { word: 'javelin', zh: '标枪', phonetic: '/ˈdʒævlɪn/' },
  { word: 'kayaking', zh: '皮划艇', phonetic: '/ˈkaɪækɪŋ/' },
  { word: 'lacrosse', zh: '长曲棍球', phonetic: '/ləˈkrɒs/' },
  { word: 'marathon', zh: '马拉松', phonetic: '/ˈmærəθən/' },
  // 👩‍🚒 奇妙职业
  { word: 'artist', zh: '艺术家', phonetic: '/ˈɑːtɪst/' },
  { word: 'builder', zh: '建筑工人', phonetic: '/ˈbɪldər/' },
  { word: 'captain', zh: '船长/队长', phonetic: '/ˈkæptɪn/' },
  { word: 'dancer', zh: '舞蹈家', phonetic: '/ˈdɑːnsər/' },
  { word: 'doctor', zh: '医生', phonetic: '/ˈdɒktər/' },
  { word: 'farmer', zh: '农民', phonetic: '/ˈfɑːmər/' },
  { word: 'firefighter', zh: '消防员', phonetic: '/ˈfaɪərfaɪtər/' },
  { word: 'hunter', zh: '猎人', phonetic: '/ˈhʌntər/' },
  { word: 'knight', zh: '骑士', phonetic: '/naɪt/' },
  { word: 'nurse', zh: '护士', phonetic: '/nɜːs/' },
  { word: 'pilot', zh: '飞行员', phonetic: '/ˈpaɪlət/' },
  { word: 'teacher', zh: '老师', phonetic: '/ˈtiːtʃər/' },
  { word: 'chemist', zh: '化学家', phonetic: '/ˈkɛmɪst/' },
  { word: 'composer', zh: '作曲家', phonetic: '/kəmˈpəʊzər/' },
  { word: 'designer', zh: '设计师', phonetic: '/dɪˈzaɪnər/' },
  { word: 'director', zh: '导演', phonetic: '/dɪˈrɛktər/' },
  { word: 'engineer', zh: '工程师', phonetic: '/ˌɛndʒɪˈnɪər/' },
  { word: 'explorer', zh: '探险家', phonetic: '/ɪkˈsplɔːrər/' },
  { word: 'inventor', zh: '发明家', phonetic: '/ɪnˈvɛntər/' },
  { word: 'musician', zh: '音乐家', phonetic: '/mjuːˈzɪʃən/' },
  { word: 'painter', zh: '画家', phonetic: '/ˈpeɪntər/' },
  { word: 'sculptor', zh: '雕塑家', phonetic: '/ˈskʌlptər/' },
  // 🦄 神奇动物
  { word: 'cheetah', zh: '猎豹', phonetic: '/ˈtʃiːtə/' },
  { word: 'dolphin', zh: '海豚', phonetic: '/ˈdɒlfɪn/' },
  { word: 'flamingo', zh: '火烈鸟', phonetic: '/fləˈmɪŋɡəʊ/' },
  { word: 'giraffe', zh: '长颈鹿', phonetic: '/dʒɪˈrɑːf/' },
  { word: 'hamster', zh: '仓鼠', phonetic: '/ˈhæmstər/' },
  { word: 'leopard', zh: '豹子', phonetic: '/ˈlɛpəd/' },
  { word: 'lobster', zh: '龙虾', phonetic: '/ˈlɒbstər/' },
  { word: 'octopus', zh: '章鱼', phonetic: '/ˈɒktəpəs/' },
  { word: 'penguin', zh: '企鹅', phonetic: '/ˈpɛŋɡwɪn/' },
  { word: 'platypus', zh: '鸭嘴兽', phonetic: '/ˈplætɪpəs/' },
  { word: 'squirrel', zh: '松鼠', phonetic: '/ˈskwɪrəl/' },
  { word: 'tortoise', zh: '陆龟', phonetic: '/ˈtɔːtəs/' },
  { word: 'alligator', zh: '短吻鳄', phonetic: '/ˈælɪɡeɪtər/' },
  { word: 'armadillo', zh: '犰狳', phonetic: '/ˌɑːməˈdɪləʊ/' },
  { word: 'capybara', zh: '水豚', phonetic: '/ˌkæpɪˈbɑːrə/' },
  { word: 'chameleon', zh: '变色龙', phonetic: '/kəˈmiːliən/' },
  { word: 'cockatoo', zh: '凤头鹦鹉', phonetic: '/ˈkɒkətuː/' },
  { word: 'hedgehog', zh: '刺猬', phonetic: '/ˈhɛdʒhɒɡ/' },
  { word: 'jellyfish', zh: '水母', phonetic: '/ˈdʒɛlifɪʃ/' },
  { word: 'kangaroo', zh: '袋鼠', phonetic: '/ˌkæŋɡəˈruː/' },
  { word: 'wolverine', zh: '狼獾', phonetic: '/ˈwʊlvəriːn/' },
  // 🚀 太空宇宙
  { word: 'asteroid', zh: '小行星', phonetic: '/ˈæstərɔɪd/' },
  { word: 'comet', zh: '彗星', phonetic: '/ˈkɒmɪt/' },
  { word: 'cosmos', zh: '宇宙', phonetic: '/ˈkɒzmɒs/' },
  { word: 'eclipse', zh: '日食/月食', phonetic: '/ɪˈklɪps/' },
  { word: 'galaxy', zh: '星系', phonetic: '/ˈɡæləksi/' },
  { word: 'gravity', zh: '重力', phonetic: '/ˈɡrævɪti/' },
  { word: 'meteor', zh: '流星', phonetic: '/ˈmiːtiər/' },
  { word: 'nebula', zh: '星云', phonetic: '/ˈnɛbjʊlə/' },
  { word: 'orbit', zh: '轨道', phonetic: '/ˈɔːbɪt/' },
  { word: 'planet', zh: '行星', phonetic: '/ˈplænɪt/' },
  { word: 'rocket', zh: '火箭', phonetic: '/ˈrɒkɪt/' },
  { word: 'satellite', zh: '卫星', phonetic: '/ˈsætəlaɪt/' },
  { word: 'aurora', zh: '极光', phonetic: '/ɔːˈrɔːrə/' },
  { word: 'cosmonaut', zh: '宇航员', phonetic: '/ˈkɒzmənɔːt/' },
  { word: 'hydrogen', zh: '氢元素', phonetic: '/ˈhaɪdrədʒən/' },
  { word: 'nitrogen', zh: '氮元素', phonetic: '/ˈnaɪtrədʒən/' },
  { word: 'pulsar', zh: '脉冲星', phonetic: '/ˈpʌlsɑː/' },
  { word: 'quasar', zh: '类星体', phonetic: '/ˈkweɪzɑː/' },
  { word: 'stardust', zh: '星尘', phonetic: '/ˈstɑːdʌst/' },
  { word: 'supernova', zh: '超新星', phonetic: '/ˌsuːpəˈnəʊvə/' },
  { word: 'telescope', zh: '望远镜', phonetic: '/ˈtɛlɪskəʊp/' },
  // 🧙 魔法与奇幻
  { word: 'adventure', zh: '冒险', phonetic: '/ədˈvɛntʃər/' },
  { word: 'butterfly', zh: '蝴蝶', phonetic: '/ˈbʌtəflaɪ/' },
  { word: 'carnival', zh: '嘉年华', phonetic: '/ˈkɑːnɪvəl/' },
  { word: 'celebrate', zh: '庆祝', phonetic: '/ˈsɛlɪbreɪt/' },
  { word: 'chocolate', zh: '巧克力', phonetic: '/ˈtʃɒklɪt/' },
  { word: 'dinosaur', zh: '恐龙', phonetic: '/ˈdaɪnəsɔː/' },
  { word: 'discovery', zh: '发现', phonetic: '/dɪˈskʌvəri/' },
  { word: 'elephant', zh: '大象', phonetic: '/ˈɛlɪfənt/' },
  { word: 'fantastic', zh: '太棒了', phonetic: '/fænˈtæstɪk/' },
  { word: 'friendship', zh: '友谊', phonetic: '/ˈfrɛndʃɪp/' },
  { word: 'treasure', zh: '宝藏', phonetic: '/ˈtrɛʒər/' },
  { word: 'wonderful', zh: '美妙的', phonetic: '/ˈwʌndəfəl/' },
  { word: 'champion', zh: '冠军', phonetic: '/ˈtʃæmpiən/' },
  { word: 'courage', zh: '勇气', phonetic: '/ˈkʌrɪdʒ/' },
  { word: 'crystal', zh: '水晶', phonetic: '/ˈkrɪstəl/' },
  { word: 'curiosity', zh: '好奇心', phonetic: '/ˌkjʊəriˈɒsɪti/' },
  { word: 'dreaming', zh: '做梦', phonetic: '/ˈdriːmɪŋ/' },
  { word: 'emerald', zh: '翡翠', phonetic: '/ˈɛmərəld/' },
  { word: 'enchanted', zh: '被施了魔法的', phonetic: '/ɪnˈtʃɑːntɪd/' },
  { word: 'fairytale', zh: '童话故事', phonetic: '/ˈfɛəriteɪl/' },
  { word: 'fireworks', zh: '烟火', phonetic: '/ˈfaɪərwɜːks/' },
]

/* ─── 每关随机抽取的词数配置 ─────────────────────────────────────── */
export const levelWordCount: Record<string, number[]> = {
  easy: [10, 10, 12, 12, 14],
  normal: [10, 12, 12, 14, 14],
  hard: [8, 10, 10, 12, 12],
}

/* ─── 根据难度和关卡随机生成词列表（每次调用结果不同） ──────────── */
export function generateLevelWords(difficulty: string, levelIdx: number): WordItem[] {
  const poolMap: Record<string, WordItem[]> = {
    easy: easyPool,
    normal: normalPool,
    hard: hardPool,
  }
  const countMap = levelWordCount[difficulty] ?? levelWordCount['normal']
  const count = countMap[Math.min(levelIdx, countMap.length - 1)]
  return pickRandom(poolMap[difficulty] ?? normalPool, count)
}

/** 难度元数据 */
export const difficultyMeta = [
  { id: 'easy', name: '简单', timeLimit: 60, desc: '短词入门，动物颜色' },
  { id: 'normal', name: '普通', timeLimit: 50, desc: '水果食物，趣味词汇' },
  { id: 'hard', name: '挑战', timeLimit: 45, desc: '较长单词，扩展词汇' },
] as const
